# MASTER - Weather Download

<font color='red'>**NOTE!** 
<br/>- ensure a suitable download location is specified below (export_path)
<br/>- ensure an active API key specified below
<br/>  An API key can be obtained from worldweatheronline.com, sign up for a free 60 day account to receive a key
<br/> 
<br/> **WARNING**
<br/>  This can be a very slow process, especially for long time frames. 
<br/>  It is also prone to download failure, either due to request detail mismatch (unavailable locality) or from random time out with the server. 
<br/>  Monitor the process and amend request range if error occurs

---
---

#### import/export paths

In [1]:
import os
import pandas as pd
    
import_path = r'C:\CP\UNI\S2\jupyter\SIT764_jupyter\exports'
export_path = r'C:\CP\UNI\S2\jupyter\SIT764_jupyter\exports'

### API KEY

In [1]:
api_key = 'insert your API key in quotes here'

#### import fire localities list
fire_locats.csv file is created in data_merge notebook - it is created from the fire.csv file

In [62]:
file = 'fire_locats.csv'
vars()[file[0:-4]] = pd.read_csv('\\'.join([import_path,file[:]]))
vars()[file[0:-4]]

,lat_suburb,long_suburb,suburb,region,state
0,-35.27767,149.11829,Acton,Australian Capital Territory,Australian Capital Territory
1,-34.91119,138.70735,Adelaide Hills,Adelaide Hills,South Australia
2,-35.00310,117.86595,Albany,Albany,Western Australia
3,-34.85925,138.52138,Alberton,Port Adelaide Enfield,South Australia
4,-35.28333,138.48333,Aldinga,Onkaparinga,South Australia
...,...,...,...,...,...
1089,-23.12683,150.74406,Yeppoon,Rockhampton,Queensland
1090,-31.88809,116.76780,York,York,Western Australia
1091,-16.80278,145.72083,Yorkeys Knob,Cairns,Queensland
1092,-34.31350,148.30107,Young,Young,New South Wales
1093,-27.35591,153.04453,Zillmere,Brisbane,Queensland

Adding concatenated text to call location from weather API  
locality or lat-long can be used  
lat-long should be less prone to error

In [73]:
fire_locats['download_locality'] = fire_locats.agg('{0[suburb]},{0[state]},Australia'.format, axis=1)
fire_locats['download_lat_long'] = fire_locats.agg('{0[lat_suburb]},{0[long_suburb]}'.format, axis=1)
fire_locats = fire_locats.sort_values(['download_lat_long'], ascending=True).reset_index(drop=True)
fire_locats

,lat_suburb,long_suburb,suburb,region,state,download_locality,download_lat_long
0,-10.57937,142.21686,Thursday Island,Torres,Queensland,"Thursday Island,Queensland,Australia","-10.579369999999999,142.21686"
1,-12.18652,136.78201,Nhulunbuy,East Arnhem,Northern Territory,"Nhulunbuy,Northern Territory,Australia","-12.18652,136.78201"
2,-12.36667,130.90000,Leanyer,Darwin,Northern Territory,"Leanyer,Northern Territory,Australia","-12.36667,130.9"
3,-12.38299,130.85170,Nightcliff,Darwin,Northern Territory,"Nightcliff,Northern Territory,Australia","-12.38299,130.8517"
4,-12.42032,130.85506,Ludmilla,Darwin,Northern Territory,"Ludmilla,Northern Territory,Australia","-12.42032,130.85506"
...,...,...,...,...,...,...,...
1089,-43.03124,147.04813,Huonville,Huon Valley,Tasmania,"Huonville,Tasmania,Australia","-43.031240000000004,147.04813000000001"
1090,-43.08884,147.00906,Franklin,Huon Valley,Tasmania,"Franklin,Tasmania,Australia","-43.088840000000005,147.00906"
1091,-43.12623,147.24641,Kettering,Kingborough,Tasmania,"Kettering,Tasmania,Australia","-43.12623,147.24641"
1092,-43.15333,147.07253,Cygnet,Huon Valley,Tasmania,"Cygnet,Tasmania,Australia","-43.15333,147.07253"
1093,-43.16337,146.92549,Geeveston,Huon Valley,Tasmania,"Geeveston,Tasmania,Australia","-43.16337,146.92549"

---
---
---

## Weather Download by LAT,LONG
### RECOMMENDED

#### Generate list of lat_long values to call from weather service

In [65]:
latlong_list = fire_locats.download_lat_long.unique().tolist()
print('length =',len(latlong_list))
print('\nSAMPLE')
latlong_list[:5]

length = 1094

SAMPLE

['-35.27767,149.11829',
 '-34.911190000000005,138.70735',
 '-35.0031,117.86595',
 '-34.85925,138.52138',
 '-35.28333,138.48333']

#### Weather Download by LAT,LONG

In [ ]:
#https://www.worldweatheronline.com/developer/my/subscription/   - free subscription required for api_key (defined in cell 2)
from wwo_hist import retrieve_hist_data

# download path is defined in Cell 1 - export_path variable
os.chdir(export_path)

# this is number of hours between measurements - 24 = daily results
frequency=24                                            

start_date = '1-SEP-2014'
end_date = '30-NOV-2020'
location_list = latlong_list[:]   # modify the range in [:] to select fewer suburbs

hist_weather_data = retrieve_hist_data(api_key, location_list, start_date, end_date, frequency,
                                       location_label = True, export_csv = True, store_df = False)

---
---
---

## Data to fix T1 2021
### These suburbs have not been downloaded due to being unavailable by suburb name - need to try again using lat-long

In [53]:
# suburbs that not available from worldweatheronline.com
to_get_list1 = ['Athelstone','Balcatta','Blackett','Brassall','Breakwater','Carindale','Carramar','Chidlow','Coolaroo','Corlette','Currambine','Eumemmerring','Joondalup','Kaleen','Kealba','Kewdale','Koomooloo','Koonawarra',
'Kurunjang','Murrumbeena','Narraweena','Oxenford','Paramatta','Parmelia','Pullenvale','Scheyville','Seaholme','Tapping','Telopea','Tinbeerwah','Tootgarook','Windale','Yamanto','Yangebup','Beeliar','Charmhaven','Cooroibah',
'Delacombe','Dynnyrne','Glendenning','Heyfield','Highvale','Moranbah','Nickol','Nulsen','Rangeville','Zillmere']

# suburbs that produce incorrect data - even when ,Australia is added to the request
to_get_list2 = ['Acton','Adelaide Hills','Alberton','Alexander Heights','Alexandria','Allambie Heights','Arcadia vale','Ashwood',
'Beaumont Hills','Bell Park','bell post hill','Belmont North','Bertram','Bibra Lake','Black Hill','Black Rock','Blind Bight','Bohle Plains','Botanic Ridge','Brookfield','Brown Hill','Buff Point','Burbank','Burnside Heights',
'Calderwood','Camden South','Canning Vale','Caroline Springs','Casuarina','Cedar Vale','Church Point','City of Cockburn','Clarkson','Clear Island Waters','Cordeaux Heights','Croom','Deebing Heights','East Lismore','East Ryde',
'East Victoria Park','Ermington','Fairfield East','Fennell Bay','Flinders View','Forrest','Gateshead','Glen Alpine','glen iris','Glendale','Glenmore Park','Granton','Hamlyn Heights','Hammond Park','Harrisdale','Heatherton',
'Henley Brook','Hillman','hillside','Howrah','Inala','Ingleside','Junction Village','Kenmore Hills','Kingfisher Shores','Lakelands','Launching Place','Little Hampton','Little Mountain','Logan Reserve','Loveday','Lynbrook',
'Macarthur','Macmasters Beach','Macquarie','Magnetic Island','Maida Vale','Mango Hill','Maryborough','Midland','Mill Park','Millars Well','Moe','Monkland','Mount Nathan','Nathan','North Booval','North Maclean','Oakford',
'Orelia','Palmyra','Park Orchards','Park Ridge South','Patterson Lakes','Phillip Island','Port Kennedy','Port Stephens','Pottsville Beach','Ridgewood','Robertson','Sadliers Crossing','Safety Beach','Samson','Sandhurst',
'Secret Harbour','Seventeen Mile Rocks','Seville Grove','Silkstone','Sinagra','Soldiers Hill','South Kingsville','South Windsor','South Yunderup','Springfield','Springfield Lakes','Springwood','Stratton','Success',
'Summerhill','Taringa','The Vines','Thursday Island','Tieri','Tivoli','Top Camp','Twin Waters','Varsity Lakes','Wandana Heights','Waterways','Wattle Park','Wavell Heights','Werrington County','williams landing',
'Wilsonton Heights','Woodbridge','Woodville North','Wyndham Vale']

to_get_list = to_get_list1 + to_get_list2
len(to_get_list)

183

#### Filter fire_locats for suburbs that have not been downloaded (list above)

In [74]:
fire_locats_to_get = fire_locats[fire_locats.suburb.isin(to_get_list)].reset_index(drop=True)
fire_locats_to_get

,lat_suburb,long_suburb,suburb,region,state,download_locality,download_lat_long
0,-10.57937,142.21686,Thursday Island,Torres,Queensland,"Thursday Island,Queensland,Australia","-10.579369999999999,142.21686"
1,-19.15514,146.84850,Magnetic Island,Townsville,Queensland,"Magnetic Island,Queensland,Australia","-19.15514,146.8485"
2,-19.31365,146.69186,Bohle Plains,Townsville,Queensland,"Bohle Plains,Queensland,Australia","-19.31365,146.69186000000002"
3,-20.74168,116.81731,Millars Well,Roebourne,Western Australia,"Millars Well,Western Australia,Australia","-20.74168,116.81731"
4,-20.74558,116.79540,Nickol,Roebourne,Western Australia,"Nickol,Western Australia,Australia","-20.74558,116.7954"
...,...,...,...,...,...,...,...
176,-38.48349,145.23102,Phillip Island,Bass Coast,Victoria,"Phillip Island,Victoria,Australia","-38.48349,145.23102"
177,-41.46747,147.12796,Summerhill,Launceston,Tasmania,"Summerhill,Tasmania,Australia","-41.46747,147.12796"
178,-42.75149,147.22795,Granton,Glenorchy,Tasmania,"Granton,Tasmania,Australia","-42.751490000000004,147.22795"
179,-42.88728,147.40554,Howrah,Clarence,Tasmania,"Howrah,Tasmania,Australia","-42.88728,147.40554"
180,-42.90541,147.31576,Dynnyrne,Hobart,Tasmania,"Dynnyrne,Tasmania,Australia","-42.905409999999996,147.31576"

#### Export fire locats that need weather to be acquired in T1 2021

In [75]:
file = 'fire_locats_to_get.csv'
vars()[file[0:-4]].to_csv('\\'.join([export_path,file[:]]),index = False)

#### Generate list of lat_long values to call from weather service

In [76]:
latlong_list = fire_locats_to_get.download_lat_long.unique().tolist()
print(len(latlong_list))

181

## Weather Download by LAT,LONG

In [ ]:
#https://www.worldweatheronline.com/developer/my/subscription/   - free subscription required for api_key (defined in cell 2)
from wwo_hist import retrieve_hist_data

# download path is defined in Cell 1 - export_path variable
os.chdir(export_path)

# this is number of hours between measurements - 24 = daily results
frequency=24                                            

start_date = '1-SEP-2014'
end_date = '30-NOV-2020'
location_list = latlong_list[:]   # modify the range in [:] to select fewer suburbs

hist_weather_data = retrieve_hist_data(api_key, location_list, start_date, end_date, frequency,
                                       location_label = True, export_csv = True, store_df = False)

---
---
---

## Weather Download by SUBURB
### NOT RECOMMENDED
due to locality errors and higher potential for unavailable data, this method is not recommended.  
**use download by lat,long values instead - see code lower down**

#### Suburbs that are not available or produce incorrect location data

In [28]:
# suburbs that not available from worldweatheronline.com
remove_list1 = ['Athelstone','Balcatta','Blackett','Brassall','Breakwater','Carindale','Carramar','Chidlow','Coolaroo','Corlette','Currambine','Eumemmerring','Joondalup','Kaleen','Kealba','Kewdale','Koomooloo','Koonawarra',
'Kurunjang','Murrumbeena','Narraweena','Oxenford','Paramatta','Parmelia','Pullenvale','Scheyville','Seaholme','Tapping','Telopea','Tinbeerwah','Tootgarook','Windale','Yamanto','Yangebup','Beeliar','Charmhaven','Cooroibah',
'Delacombe','Dynnyrne','Glendenning','Heyfield','Highvale','Moranbah','Nickol','Nulsen','Rangeville','Zillmere']

# suburbs that produce incorrect data - even when ,Australia is added to the request
remove_list2 = ['Acton','Adelaide Hills','Alberton','Alexander Heights','Alexandria','Allambie Heights','Arcadia vale','Ashwood',
'Beaumont Hills','Bell Park','bell post hill','Belmont North','Bertram','Bibra Lake','Black Hill','Black Rock','Blind Bight','Bohle Plains','Botanic Ridge','Brookfield','Brown Hill','Buff Point','Burbank','Burnside Heights',
'Calderwood','Camden South','Canning Vale','Caroline Springs','Casuarina','Cedar Vale','Church Point','City of Cockburn','Clarkson','Clear Island Waters','Cordeaux Heights','Croom','Deebing Heights','East Lismore','East Ryde',
'East Victoria Park','Ermington','Fairfield East','Fennell Bay','Flinders View','Forrest','Gateshead','Glen Alpine','glen iris','Glendale','Glenmore Park','Granton','Hamlyn Heights','Hammond Park','Harrisdale','Heatherton',
'Henley Brook','Hillman','hillside','Howrah','Inala','Ingleside','Junction Village','Kenmore Hills','Kingfisher Shores','Lakelands','Launching Place','Little Hampton','Little Mountain','Logan Reserve','Loveday','Lynbrook',
'Macarthur','Macmasters Beach','Macquarie','Magnetic Island','Maida Vale','Mango Hill','Maryborough','Midland','Mill Park','Millars Well','Moe','Monkland','Mount Nathan','Nathan','North Booval','North Maclean','Oakford',
'Orelia','Palmyra','Park Orchards','Park Ridge South','Patterson Lakes','Phillip Island','Port Kennedy','Port Stephens','Pottsville Beach','Ridgewood','Robertson','Sadliers Crossing','Safety Beach','Samson','Sandhurst',
'Secret Harbour','Seventeen Mile Rocks','Seville Grove','Silkstone','Sinagra','Soldiers Hill','South Kingsville','South Windsor','South Yunderup','Springfield','Springfield Lakes','Springwood','Stratton','Success',
'Summerhill','Taringa','The Vines','Thursday Island','Tieri','Tivoli','Top Camp','Twin Waters','Varsity Lakes','Wandana Heights','Waterways','Wattle Park','Wavell Heights','Werrington County','williams landing',
'Wilsonton Heights','Woodbridge','Woodville North','Wyndham Vale']

remove_list = remove_list1 + remove_list2
len(remove_list)

183

#### remove problematic suburbs

In [34]:
download_suburbs = fire_locats[~fire_locats.suburb.isin(remove_list)].sort_values(['suburb'], ascending=True).reset_index(drop=True) 
len(download_suburbs)
download_suburbs

,lat_suburb,long_suburb,suburb,region,state,download_locality,download_lat_long
0,-35.00310,117.86595,Albany,Albany,Western Australia,"Albany,Western Australia,Australia","-35.0031,117.86595"
1,-35.28333,138.48333,Aldinga,Onkaparinga,South Australia,"Aldinga,South Australia,Australia","-35.28333,138.48333"
2,-37.19132,145.71120,Alexandra,Murrindindi,Victoria,"Alexandra,Victoria,Australia","-37.191320000000005,145.7112"
3,-23.69748,133.88362,Alice Springs,Alice Springs,Northern Territory,"Alice Springs,Northern Territory,Australia","-23.69748,133.88362"
4,-38.38639,142.59431,Allansford,Warrnambool,Victoria,"Allansford,Victoria,Australia","-38.386390000000006,142.59431"
...,...,...,...,...,...,...,...
908,-27.71667,153.21667,Yatala,Gold Coast,Queensland,"Yatala,Queensland,Australia","-27.71667,153.21667"
909,-23.12683,150.74406,Yeppoon,Rockhampton,Queensland,"Yeppoon,Queensland,Australia","-23.126829999999998,150.74406000000002"
910,-31.88809,116.76780,York,York,Western Australia,"York,Western Australia,Australia","-31.888090000000002,116.7678"
911,-16.80278,145.72083,Yorkeys Knob,Cairns,Queensland,"Yorkeys Knob,Queensland,Australia","-16.80278,145.72083"
912,-34.31350,148.30107,Young,Young,New South Wales,"Young,New South Wales,Australia","-34.3135,148.30106999999998"

#### Create list of download suburbs
#### replace spaces with %20 to generate correct address call to weather server
the %20 text is removed in the data merge process (T3_2020_Master_data_merge.ipynb)

In [52]:
download_list = download_suburbs.download_locality.unique().tolist()
print(len(download_list))

suburbs = []
for string in download_list:
    suburb = string.replace(" ", "%20")
    suburbs.append(suburb)

print(download_list[3],' = ',suburbs[3],'\n')
print('SAMPLE')
suburbs[0:5]

913
Alice Springs,Northern Territory,Australia  =  Alice%20Springs,Northern%20Territory,Australia

SAMPLE

['Albany,Western%20Australia,Australia',
 'Aldinga,South%20Australia,Australia',
 'Alexandra,Victoria,Australia',
 'Alice%20Springs,Northern%20Territory,Australia',
 'Allansford,Victoria,Australia']

## Weather Download by SUBURB

In [ ]:
#https://www.worldweatheronline.com/developer/my/subscription/   - free subscription required for api_key (defined in cell 2)
from wwo_hist import retrieve_hist_data

# download path is defined in Cell 1 - export_path variable
os.chdir(export_path)

# this is number of hours between measurements - 24 = daily results
frequency=24                                            

start_date = '1-SEP-2014'
end_date = '30-NOV-2020'
location_list = suburbs[:]   # modify the range in [:] to select fewer suburbs

hist_weather_data = retrieve_hist_data(api_key, location_list, start_date, end_date, frequency,
                                       location_label = True, export_csv = True, store_df = False)